algoritmo "condicoesecomparadores"
var
   num1, num2, result:inteiro
inicio
   escreval("Digite os números abaixo:")
   leia(num1,num2)
   result <- num1 + num2
   se (result > 10) entao
   escreval("O número é maior que 10!")
   senao
   escreval("O número é menor que 10!")
   fimse
fimalgoritmo

// operadores comparacionais
// >, <, <>, >=, <=, =

// condicionais
// se, senao, fimse