algoritmo "math1"
var
   nota1, nota2, nota3, nota4, result:real
inicio
      escreval("Digite a sua primeira nota:")
      leia(nota1)
      escreval("Digite a sua segunda nota:")
      leia(nota2)
      escreval("Digite a sua terceira nota:")
      leia(nota3)
      escreval("Digite a sua quarta nota:")
      leia(nota4)
      result <- (nota1 + nota2 + nota3 + nota4) / 4
      escreva("A média das suas notas dá em:",result)
fimalgoritmo